[package]
name = "razer_keyboard_mode_changer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
razer_driver_rs = "0.1.0"
anyhow = "1.0"